//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module Features.Base {
  export interface IBaseResult
  {
    isSuccessful: boolean;
    message: string;
    errors: { [key:string]: string };
  }
}
module Features.Account {
  export interface ILoginCommand
  {
    email: string;
    password: string;
    rememberMe: boolean;
  }
  export interface ILoginResult extends Features.Base.IBaseResult
  {
    requiresTwoFactor: boolean;
    isLockedOut: boolean;
    requiresEmailConfirmation: boolean;
    token: string;
  }
  export interface IResetPasswordCommand
  {
    code: string;
    email: string;
    password: string;
    confirmPassword: string;
  }
}
module Features.Account.Manage {
  export interface IMfaEnableResult extends Features.Base.IBaseResult
  {
    sharedKey: string;
    authenticatorUri: string;
    qrCodeBase64: string;
  }
  export interface IMfaInfo extends Features.Base.IBaseResult
  {
    hasAuthenticator: boolean;
    recoveryCodesLeft: number;
    isMfaEnabled: boolean;
    isMachineRemembered: boolean;
  }
  export interface IUserProfileCommand
  {
    email: string;
    phoneNumber: string;
    isEmailConfirmed: boolean;
  }
}
